CREATE TABLE students (
    student_id VARCHAR2(50) PRIMARY KEY,
    password VARCHAR2(255),
    full_name VARCHAR2(100),
    department VARCHAR2(100),
    role VARCHAR2(20)
);

CREATE TABLE chats (
    chat_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id VARCHAR2(50),
    message CLOB,
    sender VARCHAR2(10),
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (student_id) REFERENCES students(student_id)
);